server:
  port: 8050

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access_expiry_date: ${JWT_ACCESS_EXPIRY_DATE}
  refresh_expiry_date: ${JWT_REFRESH_EXPIRY_DATE}
