server:
  port: 8050

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-expiry-date: ${JWT_ACCESS_EXPIRY_DATE}
  refresh-expiry-date: ${JWT_REFRESH_EXPIRY_DATE}
